#!/usr/bin/env node
/**
 * Build the single-file site.
 *
 * The sources stay readable ES modules (`src/vase64.js`, `app.js`) because the
 * CLI and the tests import them. A browser cannot load an ES module from
 * `file://` — the origin is `null`, so every module request is blocked as CORS
 * — so for shipping we inline the codec, the app and the stylesheet into one
 * classic <script> with no imports at all. Open it by double-clicking it.
 *
 *   node build.mjs            # writes index.html
 *
 * The inlining is deliberately dumb: strip `export `, drop the one import
 * block, and concatenate. Everything is top-level declarations, so the result
 * is a valid classic script.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const read = (name) => readFileSync(join(here, name), 'utf8');

/** Everything before this marker is the dependency-free palette + codec. */
const CODEC_MARKER = '/* -------------------------------------------------------------------------- */\n/* text <-> bytes';

/** Turn an ES module into classic-script text. */
function stripModule(source) {
  return source
    // `export const x` / `export function x` / `export class x` -> plain decls.
    .replace(/^export (?=(?:const|let|var|function|class)\b)/gm, '')
    // The one import block in app.js; the names already exist in scope.
    .replace(/^import \{[\s\S]*?\} from '[^']*';\n/m, '');
}

const codec = read('src/vase64.js');
const app = read('app.js');
const styles = read('styles.css');
const page = read('dev.html');

const markerAt = codec.indexOf(CODEC_MARKER);
if (markerAt === -1) throw new Error('codec marker not found in src/vase64.js');

// A headless sanity check can run the codec half on its own, so keep the
// boundary visible and a fixed length by padding the shorter half.
const codecPart = stripModule(codec.slice(0, markerAt)).trimEnd();
const restPart = stripModule(codec.slice(markerAt)).trimEnd();
const bundledCodec = `${codecPart}\n\n${restPart}`;

const script = [
  '/* VASE64 — generated by build.mjs. Edit src/vase64.js and app.js instead. */',
  '(function () {',
  "'use strict';",
  '',
  '// ---------------------------------------------------------------- codec',
  bundledCodec,
  '',
  '// ------------------------------------------------------------------ app',
  stripModule(app),
  '})();',
].join('\n');

if (/^\s*(import|export)\b/m.test(script)) {
  throw new Error('bundled script still contains a module statement');
}

// Parsing it here is what catches a name declared in both the codec and the
// app: sharing one scope turns a duplicated `const` into a hard syntax error.
try {
  new Function(script);
} catch (error) {
  throw new Error(`the bundled script does not parse in one scope: ${error.message}`);
}

/** The dev-only warning and its guard: the built file cannot hit this. */
const FALLBACK_BANNER = /<!--\s*\n\s*The built index\.html has this guard[\s\S]*?<\/script>\n/;

const html = page
  .replace(FALLBACK_BANNER, '')
  .replace(
    /\s*<link rel="stylesheet" href="styles\.css" \/>/,
    `\n    <style>\n${styles.trimEnd()}\n    </style>`,
  )
  .replace(
    /\s*<script type="module" src="app\.js"><\/script>/,
    `\n    <script>\n${script}\n    </script>`,
  )
  .replace(
    '<title>VASE64 — base64, but it blooms</title>',
    '<title>VASE64 — base64, but it blooms</title>\n    <!-- Single file: no imports, no build step, no network. Just open it. -->',
  );

// The dev-only warning and its guard cannot apply to a file that just works.
if (html.includes('id="protocol"')) {
  throw new Error('the dev-only protocol banner leaked into the single file');
}

// Any of these would mean the file still depends on a sibling file.
for (const reference of ['<script type="module"', '<script src=', '<link rel="stylesheet"']) {
  if (html.includes(reference)) {
    throw new Error(`single file still references an external resource: ${reference}`);
  }
}

writeFileSync(join(here, 'index.html'), html);

const kb = (text) => `${(Buffer.byteLength(text) / 1024).toFixed(1)} kB`;
console.log(`index.html  ${kb(html)}  (codec ${kb(bundledCodec)}, app ${kb(stripModule(app))})`);
